### ISSUE TITLE
Use proxies to clone repositories

### ISSUE THREAD

**Issue by Kedap** [edfloreshz/devmode#16]
**Describe the solution you'd like**
Be able to use proxies to clone repositories or obtain upstream information using proxies. This feature is to be able to obtain information depending on your locality or use services such as TOR

**Describe alternatives you've considered**
Use tools like proxychains

**Comment by edfloreshz** [comment]
Would you like to implement this?

**Comment by Kedap** [comment]
Looking at it in a better way, I see it unnecessary to add this function, because to use proxies, all you have to do is configure git globally. [article that talks about it](https://gist.github.com/evantoli/f8c23a37eb3558ab8765)
