### ISSUE TITLE
dm open not working on windows.

### ISSUE THREAD

**Issue by Demetriox** [edfloreshz/devmode#21]
**Describe the bug**
after a setup and the right enviroment variable, dm open is not working as expected and is displaying an error message. 

**To Reproduce**
1. Use devmode to clone a project.
2. Use dm cl [Project 

**Expected behavior**
Since we have code set up to open projects and Im selecting VSCode as default editor it should open the cloned repo selected when the name is available and on the path.

**Screenshots**
![image](https://user-images.githubusercontent.com/23139722/177020110-420333a6-f948-4f96-8bfc-3e0d3d9f1a48.png)

**Desktop (please complete the following information):**
 - OS: Win 11 , VS Code and Windows terminal.

**Additional context**
Project was teste on Mac/Linux and works fine. 
W11 is the OS used.
Code command is set up on eviroment viariables.
The project was rightly cloned on the path.

**Comment by edfloreshz** [comment]
Fixed with 55e6a5c6f5cd59ce5c1fe79f1b23345c86725380
