### ISSUE TITLE
Workspaces

### ISSUE THREAD

**Issue by edfloreshz** [edfloreshz/devmode#23]
**Describe the solution you'd like**
Devmode should be able to create workspaces in which to store repositories.
For example, `dm clone <repo> -w work` will clone the repository to `/home/user/Developer/GitHub/user/work/<repo>`

**Comment by lodenrogue** [comment]
Would "work" be some variable set in the config file? Or would it be a new directory in the workspace path?

**Comment by edfloreshz** [comment]
Yeah, it is an array with various workspaces, you can choose which one to use and the repo will be saved accordingly.

**Comment by edfloreshz** [comment]
Closed by the 0.3.0 release
